# Reproducibility -------------------------------------------------------------
#
# Every stochastic step in the protocol draws from an explicitly named seed
# stream. Two rules make results reproducible:
#
#   1. No function in this package leaves the caller's global RNG state
#      modified. `with_local_seed()` saves `.Random.seed`, seeds locally, and
#      restores the previous state on exit.
#   2. Sub-seeds are derived from a base seed and a *character tag* rather
#      than from a positional offset. Adding a new layer or snapshot therefore
#      does not shift the seeds of any existing one, so datasets generated by
#      different releases of the protocol stay comparable.

#' Evaluate an expression under a temporary random seed
#'
#' Seeds the random number generator, evaluates `expr`, then restores the
#' RNG state that was in effect beforehand. This keeps generation reproducible
#' without the side effect of resetting the caller's stream.
#'
#' @param seed Integer seed. If `NULL`, `expr` is evaluated with the ambient
#'   RNG state and no save/restore takes place.
#' @param expr Expression to evaluate. Evaluated lazily, after seeding.
#'
#' @return The value of `expr`.
#' @keywords internal
with_local_seed <- function(seed, expr) {
  if (is.null(seed)) {
    return(force(expr))
  }
  has_old <- exists(".Random.seed", envir = globalenv(), inherits = FALSE)
  old <- if (has_old) get(".Random.seed", envir = globalenv(), inherits = FALSE) else NULL
  on.exit(
    {
      if (is.null(old)) {
        if (exists(".Random.seed", envir = globalenv(), inherits = FALSE)) {
          rm(".Random.seed", envir = globalenv())
        }
      } else {
        assign(".Random.seed", old, envir = globalenv())
      }
    },
    add = TRUE
  )
  set.seed(as.integer(seed))
  force(expr)
}

#' Derive a named sub-seed from a base seed
#'
#' Maps a base seed and a character tag onto a stable integer seed. Tags are
#' hashed, so the seed for `"trust"` does not depend on how many other layers
#' exist or on the order in which they are generated.
#'
#' @param base Integer base seed.
#' @param tag Character tag naming the stream, e.g. `"layer:trust"`.
#'
#' @return An integer seed.
#' @keywords internal
derive_seed <- function(base, tag) {
  stopifnot(length(tag) == 1L, is.character(tag))
  bytes <- as.integer(charToRaw(tag))
  offset <- sum(bytes * seq_along(bytes) * 31L) %% 1000003L
  as.integer((as.numeric(base) + offset) %% 2147483647)
}
